### ISSUE TITLE
it broke

### ISSUE THREAD

**Issue by colemickens** [cole-mickens/wfvm#1]
The sync job broke, fyi @matthewcroughan in case you were relying on it.

**Comment by colemickens** [comment]
looks like maybe they're force pushing. I'll probably try having a "patch" and resetting and then applying the patch instead of the current strategy of rebasing.

**Comment by MatthewCroughan** [comment]
No worries, I was planning on forking this soon enough anyway. They're not maintaining it anymore. It's in need of flake-ifying anyway.

**Comment by colemickens** [comment]
I got tired of the emails from github telling me it failed, and I had to write this same thing for `wlroots-eglstreams` so I fixed it here too.
